# Site settings
title: #kuosec.fi
description: Homepage of Kuosec infosec community.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: kuosec
user_description: Infosec community located at Kuopio, Finland. Our purpose is to organize meetups and get-togethers focused on training and networking. Anyone interested in the Infosec field is welcome to join us, meet likeminded people and hopefully learn something new.
user_title: Infosec Community
email: info@kuosec.fi
twitter_username: kuosec
github_username:  kuosec
gplus_username:  kuosec

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
