# Site settings
title: Kuosec Homepage
description: Homepage of Kuosec infosec community.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KuoSec
user_description: Infosec community located at Kuopio, Finland.
user_title: Infosec community
email: neppailija@kuosec.fi
twitter_username: kuosec
github_username:  kuosec
gplus_username:  kuosec

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
